### ISSUE TITLE
Object coordinates in embedded mode

### ISSUE THREAD

**Issue by Alxblsk** [aframevr/aframe#2938]
- A-Frame Version: 0.6.1
- Platform / Device: Desktop/Mobile
- Reproducible Code Snippet or URL: https://codepen.io/Alxblsk/pen/NvpPPv

Hello all,

I've started learning A-Frame and discovered that in embedded mode clicking on a primitive may not always perform correct in cases, when a-frame container is not fully visible or container is smaller  than browser height. Please take a look on my snippet. With that margin, you can click on the empty space above primitives, but not at the bottom of them. It looks weird.

This is video I've recorded to demonstrate an issue: https://monosnap.com/file/bLZhB5MOz4ChoNy0KwY9M3r4pQzTJI

**Comment by calrk** [comment]
I've noticed this on the mouse component before, and I believe it has to do with these lines (153-154 components/cursor.js)
```
mouse.x = (evt.clientX / window.innerWidth) * 2 - 1;
mouse.y = -(evt.clientY / window.innerHeight) * 2 + 1;
```

I fixed it in the component I used by using the bounding client of the canvas to calculate the values
```
const bounds = this.el.sceneEl.canvas.getBoundingClientRect();
const width = bounds.width;
const height = bounds.height;
const left = evt.clientX - bounds.left;
const top = evt.clientY - bounds.top;

mouse.x = (left / width) * 2 - 1;
mouse.y = - (top / height) * 2 + 1;
```

**Comment by ngokevin** [comment]
Thanks! PR appreciated to use canvas size isntead in `cursor.js`. Wonder if `getBoundingClientRect` is performant to be called on every tick though.

**Comment by calrk** [comment]
Made the pull request here:
https://github.com/aframevr/aframe/pull/2942

**Comment by calrk** [comment]
@Alxblsk I think the issue you are having is part of the component you are using rather than a-frame, but for the same reason.
https://github.com/jesstelford/aframe-click-drag-component/blob/master/src/index.js#L132

**Comment by Alxblsk** [comment]
@calrk This is an example I've found in Internet, to be faster. In my own example, I do not use `aframe-click-drag-component` but still see the same issue. I'll attach another one demo soon.

**Comment by ngokevin** [comment]
Fixed using debounced window.resize handler + canvas bounding rect. https://github.com/aframevr/aframe/pull/2942
